version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: ./app
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

networks:
  net:
